[package]
name = "bl602-hal"
version = "0.1.0"
authors = ["Sipeed Co.,Ltd. <support@sipeed.com>", "Luo Jia <me@luojia.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bl602-pac = { path = "../bl602-pac" }
embedded-hal = { git = "https://github.com/rust-embedded/embedded-hal" }
embedded-time = { git = "https://github.com/FluenTech/embedded-time" }
riscv = "0.6.0"
nb = "*"
paste = "1"
num_enum = "*"